FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/balance-service ./cmd/app

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/balance-service .

EXPOSE 8080

CMD ["./balance-service"]
